var teamdatasets=[{"id":1,
"teamlogo":"milogo.jpg",
"teamname":"MUMBAI INDIANS"
,"win":5 ,
"teamshortname":"MI"},
{"id":2,
"teamlogo":"csklogo.jpg"
,"teamname":"CHENNAI SUPER KINGS",
"win":5 ,
"teamshortname":"CSK"},
{"id":3 ,
"teamlogo":"srhlogo.jpg",
"teamname":"SUNRISERS HYDERABAD"
,"win":1 ,
"teamshortname":"SRH"},
{"id":4 ,
"teamlogo":"rrlogo.png"
,"teamname":"RAJASTAN ROYALS",
"win":1,
"teamshortname":"RR"},
{"id":5,
"teamlogo":"rcblogo.png",
"teamname":"ROYAL CHALLENGERS BANGLORE"
,"win":0,
"teamshortname":"RCB"}];

var playersdatasets=[{"id":1,
"name":"ROHIT SHARMA",
"team":"MUMBAI INDIANS",
"price":"16 CRORE",
"pic":"rohit.png",
"position":"CAPTAIN"
,"role":"BATSMAN",
"stn":"MI"},

{"id":2 ,
"name":"ISHAN KISHAN",
"team":"MUMBAI INDIANS",
"price":"5.25 CRORE",
"pic":"ishan.png",
"position":"TEAM MEMBER",
"role":"BATSMAN",
"stn":"MI"},

{"id":3 ,
"name":"SURYA KUMAR YADAV",
"team":"MUMBAI INDIANS",
"price":"8 CRORE",
"pic":"sky.png",
"position":"TEAM MEMBER",
"role":"ALL ROUNDER",
"stn":"MI"},

{"id":4 ,
"name":"ARJUN TENDULKAR",
"team":"MUMBAI INDIANS",
"price":"30 LAKH",
"pic":"arjun.png",
"position":"TEAM MEMBER",
"role":"BOWLER",
"stn":"MI"},

{"id":5 ,
"name":"COMERON GREEN",
"team":"MUMBAI INDIANS",
"price":"17.5 CRORE",
"pic":"cameron.png",
"position":"TEAM MEMBER",
"role":"ALL ROUNDER",
"stn":"MI"},

{"id":6 ,
"name":"PIYUSH CHAWLA",
"team":"MUMBAI INDIANS",
"price":"50 LAKHS",
"pic":"piyush.png",
"position":"TEAM MEMBER",
"role":"ALL ROUNDER",
"stn":"MI"},

{"id":7 ,
"name":"M S DHONI",
"team":"CHENNAI SUPER KINGS",
"price":"12 CRORE",
"pic":"dhoni.png",
"position":"CAPTAIN",
"role":"WICKET KEEPER",
"stn":"CSK"},

{"id":8 ,
"name":"RAVINDRA JADEJA",
"team":"CHENNAI SUPER KINGS",
"price":"16 CRORE",
"pic":"jadeja.png",
"position":"TEAM MEMBER",
"role":"ALL ROUNDER",
"stn":"CSK"},

{"id":9 ,
"name":"DEEPAK CHAHAR",
"team":"CHENNAI SUPER KINGS",
"price":"14 CRORE",
"pic":"deepak.png",
"position":"TEAM MEMBER",
"role":"BOWLER",
"stn":"CSK"},

{"id":10 ,
"name":"RUTURAJ GAIKWAD",
"team":"CHENNAI SUPER KINGS",
"price":"6 CR",
"pic":"gaikwad.png",
"position":"TEAM MEMBER",
"role":"BOWLER",
"stn":"CSK"},

{"id":11 ,
"name":"AJINKYA RAHANE",
"team":"CHENNAI SUPER KINGS",
"price":"50 LAKH",
"pic":"ajinkya.png",
"position":"TEAM MEMBER",
"role":"BATSMAN",
"stn":"CSK"},

{"id":12 ,
"name":"MITCHELL SANTOR",
"team":"CHENNAI SUPER KINGS",
"price":"1.90 CRORE",
"pic":"santer.png",
"position":"TEAM MEMBER",
"role":"ALL ROUNDER",
"stn":"CSK"},

{"id":13 ,
"name":"UPENDRA SINGH YADAV",
"team":"SUNRISERS HYDERABAD",
"price":"25 LAKHS",
"pic":"upendra.png",
"position":"TEAM MEMBER",
"role":"WICKET KEEPER",
"stn":"SRH"},

{"id":14 ,
"name":"BHUVANESHWAR",
"team":"SUNRISERS HYDERABAD",
"price":"4.2 CRORE",
"pic":"bhuvneshwar.png",
"position":"TEAM MEMBER",
"role":"BOWLER",
"stn":"SRH"},

{"id":15 ,
"name":"MAYANK MARKHANDE",
"team":"SUNRISERS HYDERABAD",
"price":"50 LAKH",
"pic":"markande.png",
"position":"TEAM MEMBER",
"role":"BOWLER",
"stn":"SRH"},

{"id":16 ,
"name":"ANMOL PREET SINGH",
"team":"SUNRISERS HYDERABAD",
"price":"20 LAKH",
"pic":"anmol.png",
"position":"TEAM MEMBER",
"role":"BATSMAN",
"stn":"SRH"},

{"id":17 ,
"name":"MAYANK AGARWAL",
"team":"SUNRISERS HYDERABAD",
"price":"8.25 CRORE",
"pic":"agarwal.png",
"position":"TEAM MEMBER",
"role":"BATSMAN",
"stn":"SRH"},

{"id":18 ,
"name":"WASHINGTON SUNDAR",
"team":"SUNRISERS HYDERABAD",
"price":"8.75 CRORE",
"pic":"sundar.png",
"position":"TEAM MEMBER",
"role":"ALL ROUNDER",
"stn":"SRH"},

{"id":19 ,
"name":"SANJU SAMSON",
"team":"RAJASTAN ROYALS",
"price":"6.5 CRORE",
"pic":"sanju.png",
"position":"CAPTAIN",
"role":"WICKET KEEPER",
"stn":"RR"},

{"id":20 ,
"name":"YUZVENDRA CHAHAL",
"team":"RAJASTAN ROYALS",
"price":"5 CRORE",
"pic":"chahal.png",
"position":"TEAM MEMBER",
"role":"BOWLER",
"stn":"RR"},

{"id":21 ,
"name":"R ASHWIN",
"team":"RAJASTAN ROYALS",
"price":"5 CRORE",
"pic":"ashwin.png",
"position":"TEAM MEMBER",
"role":"BOWLER",
"stn":"RR"},

{"id":22 ,
"name":"JOS BUTTLER",
"team":"RAJASTAN ROYALS",
"price":"10 CRORE",
"pic":"jos.png",
"position":"TEAM MEMBER",
"role":"BATSMAN",
"stn":"RR"},

{"id":23 ,
"name":"YASHASVI JAISWAL",
"team":"RAJASTAN ROYALS",
"price":"4 CRORE",
"pic":"yashavi.png",
"position":"TEAM MEMBER",
"role":"BATSMAN",
"stn":"RR"},

{"id":24 ,
"name":"SHINRANN HETMYER",
"team":"RAJASTAN ROYALS",
"price":"10 CRORE",
"pic":"hetmyer.png",
"position":"TEAM MEMBER",
"role":"BATSMAN",
"stn":"RR"},

{"id":25 ,
"name":"VIRAT KOHLI",
"team":"ROYAL CHALLENGERS BANGLORE",
"price":"15 CRORE"
,"pic":"virat.png",
"position":"CAPTAIN",
"role":"BATSMAN",
"stn":"RCB"},

{"id":26 ,
"name":"DINESH KARTIK",
"team":"ROYAL CHALLENGERS BANGLORE",
"price":"5.5 CRORE",
"pic":"dinesh.png",
"position":"TEAM MEMBER",
"role":"WICKET KEEPER",
"stn":"RCB"},

{"id":27 ,
"name":"SONU YADAV",
"team":"ROYAL CHALLENGERS BANGLORE",
"price":"20 LAKH",
"pic":"sonu.png",
"position":"TEAM MEMBER",
"role":"ALL ROUNDER",
"stn":"RCB"},

{"id":28 ,
"name":"GLENN MAXWELL",
"team":"ROYAL CHALLENGERS BANGLORE",
"price":"7 CRORE",
"pic":"glenn.png",
"position":"TEAM MEMBER",
"role":"ALL ROUNDER",
"stn":"RCB"},

{"id":29 ,
"name":"M SIRAJ",
"team":"ROYAL CHALLENGERS BANGLORE",
"price":"7 CRORE",
"pic":"siraj.png",
"position":"TEAM MEMBER",
"role":"BOWLER",
"stn":"RCB"},

{"id":30 ,
"name":"MANOJ BHANDAGE",
"team":"ROYAL CHALLENGERS BANGLORE",
"price":"20 LAKH",
"pic":"manoj.png",
"position":"TEAM MEMBER",
"role":"ALL ROUNDER",
"stn":"RCB"}];



var storeteamdata=JSON.stringify(teamdatasets);
localStorage.setItem("teamdata",storeteamdata);



var storeplayersdata=JSON.stringify(playersdatasets);
localStorage.setItem("playerdata",storeplayersdata);

